version: '3.4'

services:
  fmbot:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: fmbot_bot
    volumes:
      - "./config.json:/app/configs/config.json"
    depends_on:
      - postgres

  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: fmbot_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - "./database/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
