version: '3.8'

name: 'fmbot-prod'
services:
  prod-1:
    image: ghcr.io/fmbot-discord/fmbot:main
    restart: always
    network_mode: host
    volumes:
      - /fmbot/prod/:/app/configs/
      - /fmbot/cache/:/app/cache/
    command: "--memory=30g"
    environment:
      - INSTANCE_NAME=prod-1
      - SHARDS_MAIN_INSTANCE=true
      - SHARDS_JOB_MASTER=true
      - SHARDS_TOTAL_SHARDS=336
      - SHARDS_FIRST_SHARD=0
      - SHARDS_LAST_SHARD=67

  prod-2:
    image: ghcr.io/fmbot-discord/fmbot:main
    restart: always
    network_mode: host
    volumes:
      - /fmbot/prod/:/app/configs/
      - /fmbot/cache/:/app/cache/
    command: "--memory=30g"
    depends_on:
      prod-1:
        condition: service_healthy
    environment:
      - INSTANCE_NAME=prod-2
      - SHARDS_TOTAL_SHARDS=336
      - SHARDS_FIRST_SHARD=68
      - SHARDS_LAST_SHARD=134

  prod-3:
    image: ghcr.io/fmbot-discord/fmbot:main
    restart: always
    network_mode: host
    volumes:
      - /fmbot/prod/:/app/configs/
      - /fmbot/cache/:/app/cache/
    command: "--memory=30g"
    depends_on:
      prod-2:
        condition: service_healthy
    environment:
      - INSTANCE_NAME=prod-3
      - SHARDS_TOTAL_SHARDS=336
      - SHARDS_FIRST_SHARD=135
      - SHARDS_LAST_SHARD=201

  prod-4:
    image: ghcr.io/fmbot-discord/fmbot:main
    restart: always
    network_mode: host
    volumes:
      - /fmbot/prod/:/app/configs/
      - /fmbot/cache/:/app/cache/
    command: "--memory=30g"
    depends_on:
      prod-3:
        condition: service_healthy
    environment:
      - INSTANCE_NAME=prod-4
      - SHARDS_TOTAL_SHARDS=336
      - SHARDS_FIRST_SHARD=202
      - SHARDS_LAST_SHARD=268

  prod-5:
    image: ghcr.io/fmbot-discord/fmbot:main
    restart: always
    network_mode: host
    volumes:
      - /fmbot/prod/:/app/configs/
      - /fmbot/cache/:/app/cache/
    command: "--memory=30g"
    depends_on:
      prod-4:
        condition: service_healthy
    environment:
      - INSTANCE_NAME=prod-5
      - SHARDS_TOTAL_SHARDS=336
      - SHARDS_FIRST_SHARD=269
      - SHARDS_LAST_SHARD=335
