version: '3.8'

name: 'fmbot-beta'
services:
  beta-1:
    image: ghcr.io/fmbot-discord/fmbot:dev
    restart: always
    network_mode: host
    volumes:
      - /fmbot/beta/:/app/configs/
      - /fmbot/cache/:/app/cache/
    command: "--memory=5g"
    environment:
      - INSTANCE_NAME=beta-1
      - SHARDS_MAIN_INSTANCE=true
      - SHARDS_TOTAL_SHARDS=12
      - SHARDS_FIRST_SHARD=0
      - SHARDS_LAST_SHARD=5

  beta-2:
    image: ghcr.io/fmbot-discord/fmbot:dev
    restart: always
    network_mode: host
    volumes:
      - /fmbot/beta/:/app/configs/
      - /fmbot/cache/:/app/cache/
    command: "--memory=5g"
    depends_on:
      beta-1:
        condition: service_healthy
    environment:
      - INSTANCE_NAME=beta-2
      - SHARDS_TOTAL_SHARDS=12
      - SHARDS_FIRST_SHARD=6
      - SHARDS_LAST_SHARD=11
